In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
dataset = pd.read_csv('Housing.csv')

for i, ele in enumerate(dataset):
    print(f'{i}: {ele}')
X = dataset.drop(columns=['prefarea','guestroom','hotwaterheating','basement']).iloc[:, 1:]
y = dataset.iloc[:, 0].values

y = y.reshape(len(y),1)

0: price
1: area
2: bedrooms
3: bathrooms
4: stories
5: mainroad
6: guestroom
7: basement
8: hotwaterheating
9: airconditioning
10: parking
11: prefarea
12: furnishingstatus


In [13]:
y

array([[13300000],
       [12250000],
       [12250000],
       [12215000],
       [11410000],
       [10850000],
       [10150000],
       [10150000],
       [ 9870000],
       [ 9800000],
       [ 9800000],
       [ 9681000],
       [ 9310000],
       [ 9240000],
       [ 9240000],
       [ 9100000],
       [ 9100000],
       [ 8960000],
       [ 8890000],
       [ 8855000],
       [ 8750000],
       [ 8680000],
       [ 8645000],
       [ 8645000],
       [ 8575000],
       [ 8540000],
       [ 8463000],
       [ 8400000],
       [ 8400000],
       [ 8400000],
       [ 8400000],
       [ 8400000],
       [ 8295000],
       [ 8190000],
       [ 8120000],
       [ 8080940],
       [ 8043000],
       [ 7980000],
       [ 7962500],
       [ 7910000],
       [ 7875000],
       [ 7840000],
       [ 7700000],
       [ 7700000],
       [ 7560000],
       [ 7560000],
       [ 7525000],
       [ 7490000],
       [ 7455000],
       [ 7420000],
       [ 7420000],
       [ 7420000],
       [ 735

In [14]:
X

area  bedrooms  bathrooms  stories mainroad airconditioning  parking  \
0    7420         4          2        3      yes             yes        2   
1    8960         4          4        4      yes             yes        3   
2    9960         3          2        2      yes              no        2   
3    7500         4          2        2      yes             yes        3   
4    7420         4          1        2      yes             yes        2   
..    ...       ...        ...      ...      ...             ...      ...   
540  3000         2          1        1      yes              no        2   
541  2400         3          1        1       no              no        0   
542  3620         2          1        1      yes              no        0   
543  2910         3          1        1       no              no        0   
544  3850         3          1        2      yes              no        0   

    furnishingstatus  
0          furnished  
1          furnished  
2     semi-furnished  
3          furnished  
4          furnished  
..               ...  
540      unfurnished  
541   semi-furnished  
542      unfurnished  
543        furnished  
544      unfurnished  

[545 rows x 8 columns]

In [15]:
# import preprocessing library
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# OneHotEncoder 
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['mainroad','airconditioning','furnishingstatus'])], remainder='passthrough')

# apply encoding
X = np.array(ct.fit_transform(X))

In [16]:
print(X)
# Encoded hotwaterheating and airconditioning column

[[0. 1. 0. ... 2. 3. 2.]
 [0. 1. 0. ... 4. 4. 3.]
 [0. 1. 1. ... 2. 2. 2.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [1. 0. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 2. 0.]]


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [18]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [19]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

/var/folders/06/6rnd9mvj2tg64m2vg9cssn0w0000gn/T/ipykernel_15518/572084302.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train, y_train)


RandomForestRegressor(n_estimators=10, random_state=0)

In [20]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 8144500.    7070000.  ]
 [ 5496050.    4550000.  ]
 [ 7302750.    5600000.  ]
 [ 6219500.    6125000.  ]
 [ 4374300.    2940000.  ]
 [ 3934000.    3780000.  ]
 [ 2632000.    2450000.  ]
 [ 5672100.    7490000.  ]
 [ 2792615.    2940000.  ]
 [ 4830000.    6440000.  ]
 [ 3514000.    2800000.  ]
 [ 4162550.    3325000.  ]
 [ 5479600.    5810000.  ]
 [ 4334750.    5950000.  ]
 [ 7223300.    6895000.  ]
 [ 8205176.   13300000.  ]
 [ 4319000.    3640000.  ]
 [ 3873800.    2870000.  ]
 [ 6202000.    5460000.  ]
 [ 2635500.    1890000.  ]
 [ 4128950.    3780000.  ]
 [ 6132000.    5600000.  ]
 [ 4067000.    2660000.  ]
 [ 3202500.    3640000.  ]
 [ 4889500.    2590000.  ]
 [ 4904550.    5250000.  ]
 [ 2891000.    2450000.  ]
 [ 7868000.    6930000.  ]
 [ 6765500.    9800000.  ]
 [ 3452400.    3430000.  ]
 [ 6377000.    7840000.  ]
 [ 7209300.    5950000.  ]
 [ 4158000.    3430000.  ]
 [ 5480300.    2940000.  ]
 [ 5391750.    6090000.  ]
 [ 3331300.    4620000.  ]
 [ 5142900.    4543000.  ]
 

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.5856414028973683