In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
dataset = pd.read_csv('Housing.csv')

for i, ele in enumerate(dataset):
    print(f'{i}: {ele}')
X = dataset.drop(columns=['prefarea','guestroom','hotwaterheating','basement']).iloc[:, 1:]
y = dataset.iloc[:, 0].values

y = y.reshape(len(y),1)

0: price
1: area
2: bedrooms
3: bathrooms
4: stories
5: mainroad
6: guestroom
7: basement
8: hotwaterheating
9: airconditioning
10: parking
11: prefarea
12: furnishingstatus


In [11]:
y

array([[13300000],
       [12250000],
       [12250000],
       [12215000],
       [11410000],
       [10850000],
       [10150000],
       [10150000],
       [ 9870000],
       [ 9800000],
       [ 9800000],
       [ 9681000],
       [ 9310000],
       [ 9240000],
       [ 9240000],
       [ 9100000],
       [ 9100000],
       [ 8960000],
       [ 8890000],
       [ 8855000],
       [ 8750000],
       [ 8680000],
       [ 8645000],
       [ 8645000],
       [ 8575000],
       [ 8540000],
       [ 8463000],
       [ 8400000],
       [ 8400000],
       [ 8400000],
       [ 8400000],
       [ 8400000],
       [ 8295000],
       [ 8190000],
       [ 8120000],
       [ 8080940],
       [ 8043000],
       [ 7980000],
       [ 7962500],
       [ 7910000],
       [ 7875000],
       [ 7840000],
       [ 7700000],
       [ 7700000],
       [ 7560000],
       [ 7560000],
       [ 7525000],
       [ 7490000],
       [ 7455000],
       [ 7420000],
       [ 7420000],
       [ 7420000],
       [ 735

In [12]:
X

area  bedrooms  bathrooms  stories mainroad airconditioning  parking  \
0    7420         4          2        3      yes             yes        2   
1    8960         4          4        4      yes             yes        3   
2    9960         3          2        2      yes              no        2   
3    7500         4          2        2      yes             yes        3   
4    7420         4          1        2      yes             yes        2   
..    ...       ...        ...      ...      ...             ...      ...   
540  3000         2          1        1      yes              no        2   
541  2400         3          1        1       no              no        0   
542  3620         2          1        1      yes              no        0   
543  2910         3          1        1       no              no        0   
544  3850         3          1        2      yes              no        0   

    furnishingstatus  
0          furnished  
1          furnished  
2     semi-furnished  
3          furnished  
4          furnished  
..               ...  
540      unfurnished  
541   semi-furnished  
542      unfurnished  
543        furnished  
544      unfurnished  

[545 rows x 8 columns]

In [13]:
# import preprocessing library
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# OneHotEncoder 
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['mainroad','airconditioning','furnishingstatus'])], remainder='passthrough')

# apply encoding
X = np.array(ct.fit_transform(X))

In [14]:
print(X)
# Encoded hotwaterheating and airconditioning column

[[0. 1. 0. ... 2. 3. 2.]
 [0. 1. 0. ... 4. 4. 3.]
 [0. 1. 1. ... 2. 2. 2.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [1. 0. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 2. 0.]]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [16]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [17]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/Users/engineererjojo/anaconda3/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [18]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 7933601.43  7070000.  ]
 [ 6026556.06  4550000.  ]
 [ 6291189.11  5600000.  ]
 [ 5629333.68  6125000.  ]
 [ 4870978.47  2940000.  ]
 [ 3571839.45  3780000.  ]
 [ 2364442.23  2450000.  ]
 [ 6053007.69  7490000.  ]
 [ 3152072.14  2940000.  ]
 [ 4819325.05  6440000.  ]
 [ 3388992.94  2800000.  ]
 [ 3712045.93  3325000.  ]
 [ 5186511.18  5810000.  ]
 [ 4731743.41  5950000.  ]
 [ 6065229.6   6895000.  ]
 [ 8556128.58 13300000.  ]
 [ 3837844.45  3640000.  ]
 [ 4085942.26  2870000.  ]
 [ 5392343.83  5460000.  ]
 [ 2820943.18  1890000.  ]
 [ 3841096.5   3780000.  ]
 [ 5698861.7   5600000.  ]
 [ 4698140.57  2660000.  ]
 [ 3204095.29  3640000.  ]
 [ 5003787.14  2590000.  ]
 [ 6306708.36  5250000.  ]
 [ 2964224.1   2450000.  ]
 [ 7930342.09  6930000.  ]
 [ 7472842.36  9800000.  ]
 [ 3760349.72  3430000.  ]
 [ 6350182.52  7840000.  ]
 [ 7010822.91  5950000.  ]
 [ 3853608.08  3430000.  ]
 [ 4806686.41  2940000.  ]
 [ 7060964.39  6090000.  ]
 [ 3563211.93  4620000.  ]
 [ 5601057.43  4543000.  ]
 

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6247304166777403